
---
config:
  theme: base
---
flowchart TB
    A["main()"] --> B["Create Fcd instance"]
    B --> B1["Create Color, Files, Db, TabComplete objects"] & C["clean_up()"]
    C --> D["parse_args()"]
    D --> E{"version flag?"}
    E -- Yes --> F["Exit"]
    E -- No --> G["args_handler()"]
    G --> H{"Arguments"}
    H -- alias --> I["alias_handler()"]
    H -- add --> J["add_handler()"]
    H -- delete --> K["delete_handler()"]
    H -- command --> L["command_handler()"]
    I --> M["save_for_later_execution()"]
    J --> N["Save database"]
    K --> N
    L --> N
    M --> O["End"]
    N --> O
    F --> O
    n1["To be used by separate external bash script fcd.sh"] --> M
    n1@{ shape: text}
